#!/bin/bash

php bin/hyperf.php gen:model admin
php bin/hyperf.php gen:model article
php bin/hyperf.php gen:model assignment_log
php bin/hyperf.php gen:model attachment
php bin/hyperf.php gen:model banner
php bin/hyperf.php gen:model channel
php bin/hyperf.php gen:model goods
php bin/hyperf.php gen:model income_expenses_log
php bin/hyperf.php gen:model income_log
php bin/hyperf.php gen:model menu
php bin/hyperf.php gen:model message
php bin/hyperf.php gen:model mobile
php bin/hyperf.php gen:model notice
php bin/hyperf.php gen:model order
php bin/hyperf.php gen:model product
php bin/hyperf.php gen:model rebate_log
php bin/hyperf.php gen:model recharge
php bin/hyperf.php gen:model recharge_log
php bin/hyperf.php gen:model role
php bin/hyperf.php gen:model sign
php bin/hyperf.php gen:model system
php bin/hyperf.php gen:model test_order
php bin/hyperf.php gen:model user
php bin/hyperf.php gen:model user_alipay
php bin/hyperf.php gen:model user_bank
php bin/hyperf.php gen:model user_ex
php bin/hyperf.php gen:model user_invite
php bin/hyperf.php gen:model user_vip_log
php bin/hyperf.php gen:model user_welfare_log
php bin/hyperf.php gen:model user_withdraw
php bin/hyperf.php gen:model version_upgrade
php bin/hyperf.php gen:model vip
php bin/hyperf.php gen:model walfare
